# Site
name: "ê¹€í˜„ê·œ"
title: "Fabian's Blog"
description: "UXë¥¼ ìƒê°í•˜ëŠ” Frontend ê°œë°œì ê¹€í˜„ê·œ ì…ë‹ˆë‹¤ ğŸ˜ƒ"
logo: "assets/images/fabian.png"
favicon: "assets/images/fabian.png"
baseurl: ""
url: "https://codefabian.github.io/"
google_analytics: "UA-xxxxxxxx-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
email: khg.fabian@gmail.com

# Authors
authors:
  Fabian:
    name: Fabian
    display_name: Fabian
    avatar: ""
    email: khg.fabian@gmail.com
    description: "UXë¥¼ ìƒê°í•˜ëŠ” Frontend ê°œë°œì ê¹€í˜„ê·œ ì…ë‹ˆë‹¤ ğŸ˜ƒ"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
